### ISSUE TITLE
Could not connect anymore (Invalid response, status code: 401)

### ISSUE THREAD

**Issue by TomS1985** [lostfields/python-panasonic-comfort-cloud#34] opened 2021-01-13 05:57 UTC
Hi folks,

since today I get the following error message when I try to conntect to my panasonic device:

`pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}`

Pcomfortcloud version 0.0.18 is already installed. Seems like Panasonic has updated something and pcomfortcloud couldn't connect anymore?

With the original Panasonic smartphone app I can connect normally.

Has anyone else this problem?

Thanks and best regards,
Tom

**Comment by mortenf** [comment] 2021-01-13 07:17
Duplicate of #35.

**Closed** 2021-01-13 07:46 UTC
